apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-service
  labels:
    app: country-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-service
  template:
    metadata:
      labels:
        app: country-service
    spec:
      containers:
      - name: country-service
        image: mishrarpita/country-service:latest
        ports:
        - containerPort: 5000