apiVersion: v1
kind: Service
metadata:
  name: saveditems-service
spec:
  selector:
    app: saveditems-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 8000
  type: LoadBalancer